version: '3'

volumes:
  postgres_data:

services:
  postgres_db:
    image: postgres:9.5
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    volumes:
      - /home/user/projects/task/app/:/home/task/app/