version: '3'

volumes:
  postgres_data:

services:
  postgres_db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./app:/home/task/app
  rabbit_mq:
    image: rabbitmq:latest
    env_file:
      - .env
    ports:
    - 5673:5672
    - 15673:15672
  celery_worker:
    build: .
    env_file:
      - .env
    entrypoint: ["celery", "-A", "main.celery", "worker", "--pool=solo", "-l", "INFO"]
  celery_beat:
    build: .
    env_file:
      - .env
    entrypoint: ["celery", "-A", "main.celery", "beat", "-l", "INFO"]