"""Add relationship tables user with task_result

Revision ID: 4ffae3d355f8
Revises: 75daa660ca0d
Create Date: 2021-02-19 17:32:36.600927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffae3d355f8'
down_revision = '75daa660ca0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_result', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_result', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_result', type_='foreignkey')
    op.drop_column('task_result', 'user_id')
    # ### end Alembic commands ###
