"""set not null fields task_id, user_id in table task_result

Revision ID: 53d3ae87eae3
Revises: 4ffae3d355f8
Create Date: 2021-02-20 13:25:37.999507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d3ae87eae3'
down_revision = '4ffae3d355f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_result', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_result', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_result', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_result', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
