"""Add field can_review_tasks to User model

Revision ID: 931bb5012c43
Revises: 124e8d692799
Create Date: 2021-02-07 19:23:56.199091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931bb5012c43'
down_revision = '124e8d692799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('can_review_tasks', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_review_tasks')
    # ### end Alembic commands ###
